### PR TITLE
fix proxy type text indexing Closes #13

### LINKED ISSUE #13: proxy type indexing is off
https://github.com/mozilla-extensions/proxy-monitor/blob/ced363bb658ceaa07f96b1daaf44a5dce8e34217/extension/api.js#L40-L46

https://searchfox.org/mozilla-central/rev/79f93e7a8b9aa1903f1349f2dd46fb71596f2ae9/netwerk/base/nsIProtocolProxyService.idl#281-285

I didn't notice that no "3" was in the proxy service.  We need to insert "legacy" between "pac" and "wpad"

### PR DESCRIPTION
**Pull request by mixedpuppy**

### CODE REVIEW

File: extension/api.js [hunk 1]
```diff
@@ -41,6 +41,7 @@ const PROXY_CONFIG_TYPES = [
   "direct",
   "manual",
   "pac",
+  "unused", // nsIProtocolProxyService.idl skips index 3.
```
Comment (Rob--W) [inline extension/api.js:44]: Would this increase the difficulty of the analysis?

If so, how about appending "system_real", and then documenting that "system" is actually "wpad"? The string is technically incorrect, but the results may be easier to interpret.

Comment (mixedpuppy) [reply extension/api.js:44]: No, right now system shows up as "unknown" which in the code was just a safety catch and should never happen.  wpad shows up as system, but the numbers are minuscule and will just be a touch of noise.  those with system set may be interesting but are not anything we will do anything about.
